# Generated by Django 2.2.7 on 2019-12-18 07:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hotel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='booking.Hotel')),
            ],
            options={
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('room_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.RoomType')),
            ],
            options={
                'unique_together': {('number', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Apartment')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Room')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Hotel'),
        ),
    ]
