# Generated by Django 2.2.7 on 2019-12-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='hotel',
        ),
    ]
